name: New microprocessor architecture
description: Add support for a new microprocessor architecture
title: "Architecture : "
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to request support for a new microprocessor architecture. This master issue will drive the work effort to add support.
  - type: textarea
    attributes:
      label: Open a issue in the Anax repo to update the agent-install.sh with the new microprocessor architecture.
      description: 'Paste the issue number here'
  - type: textarea
    attributes:
      label: Open a issue in the Anax repo to update the Makefiles with the new microprocessor architecture.
      description: 'Paste the issue number here'
  - type: textarea
    attributes:
      label: Open a issue in the Anax repo to add the agent binaries to [edgeNodeFIles.sh](https://github.com/open-horizon/anax/blob/master/agent-install/edgeNodeFiles.sh) so they publish to CSS
      description: 'Paste the issue number here'
  - type: textarea
    attributes:
      label: Open a issue in the Anax repo to update the Dockerfiles to build on the new microprocessor architecture.
      description: 'Paste the issue number here'
  - type: textarea
    attributes:
      label: Open a issue in the Anax repo to add the build pipelines so it arrives in [GitHub Releases](https://github.com/open-horizon/anax/releases)
      description: 'Paste the issue number here'
  - type: textarea
    attributes:
      label: Open a issue in the Documentation repo to update the docs for this new microprocessor architecture.
      description: 'Paste the issue number here'
  - type: checkboxes
      id: terms
      attributes:
        label: New microprocessor architecture Support Checklist
        description: Follow this checklist to request support for a new microprocessor architecture
        options:
          - label: Update the agent-install.sh
            required: true
          - label: Update the Makefiles
            required: true
          - label: Update the agent binaries
            required: true
          - label: Update the Dockerfiles
            required: true
          - label: Update the build pipelines
            required: true
          - label: Validate Examples on this new microprocessor architecture
            required: true
          - label: Documentation updates to support this new microprocessor architecture
            required: true
          - label: Test / Validate and modify existing tests for the anax binary on this microprocessor architecture
            required: false
