apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: __AgentNameSpace__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      serviceAccountName: agent-service-account
      volumes:
      - name: agent-etc-vol
        configMap:
          name: openhorizon-agent-config
      - name: agent-cert-volume
        secret:
          secretName: openhorizon-agent-secrets
      - name: agent-pvc-storage
        persistentVolumeClaim:
          claimName: openhorizon-agent-pvc
      containers:
      - name: anax
        image: __ImagePath__
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/default/horizon
          subPath: horizon
          name: agent-etc-vol
        - mountPath: /etc/default/cert
          name: agent-cert-volume
        - mountPath: /var/horizon
          name: agent-pvc-storage
          subPath: horizon
        - mountPath: /etc/horizon/policy.d
          name: agent-pvc-storage
          subPath: policy
        ports:
        - containerPort: 8510
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
        env:
        - name: HZN_ORG_ID
          value: __OrgId__
        - name: AGENT_NAMESPACE
          value:  __AgentNameSpace__
        - name: AGENT_CLUSTER_IMAGE_REGISTRY_HOST
          value: __ImageRegistryHost__
        - name: HZN_MGMT_HUB_CERT_PATH
          value: /etc/default/cert/agent-install.crt
